config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  root to: 'countries#random'

  get '/countries/:name', to: 'countries#show', as: 'country'

  get '/regions/:name', to: 'countries#region', as: 'region'

  post '/graphql', to: 'graphql#execute'

  post '/callback', to: 'line_bot#callback'

  post '/callback_twitter', to: 'twitter_bot#callback'
end

app/views/shared/_about_me.html.erb
<h3>I am the Covid-19 Data-Bot</h3>
<p>You can find me on LINE @636paols, on Twitter <a href="https://twitter.com/TheCovid19Data1" target="_blank">@TheCovid19Data1</a> and of course here.</p>
<p>My goal is to provide easy to access data on Covid 19,
with a particular aim at giving individuals acccess to basic data and data-analysis.
I am no expert in the fields of virology, epidemiology, nor statistics.
Just a simple bot with a simple purpose.</p>
<p>My creator is <a href="https://www.dillonwyatt.dev" target="_blank">Dillon Wyatt</a>.
A backend web-developer for a freight forwarding company called <a href="https://www.shippio.io/en" target="_blank">Shippio</a>.
This (data-collection, LINE bot, Twitter Bot, and this page) were works of passion in his off time.
If you would like to collaborate on this project, please visit the <a href="https://github.com/dostaglou/covid-19-api" target="_blank">Github Repo.</a></p>
<p>If you have any questions or comments, feel free to contact me at <a href="mailto:the.covid19bot@gmail.com">the.covid19bot@gmail.com</a></p>

app/views/shared/_country_region_select.html.erb
  <div class="d-flex justify-content-between mt-4">
    <div class="w-50">
      <h4>Select a Country</h4>
      <select class="w-100" onchange="window.location=this.value">
        <option>Select a Country</option>
        <% countries.each do |c| %>
          <option value="<%= country_path(c.name) %>"><%= c.name %></option>
        <% end %>
      </select>
    </div>
    <div class="w-50">
      <h4 class="text-right">Select a Region</h4>
      <select class="w-100" onchange="window.location=this.value">
        <option>Select a Region</option>
        <% regions.each do |r| %>
          <option value="<%= region_path(r.gsub(" ", "_")) %>"><%= r %>
        <% end %>
      </select>
    </div>
  </div>

app/views/shared/_data_box.html.erb
<div class="data-box">
  <h3 class="text-center mb-3">Data for <%= country.name %></h3>
  <%= render 'shared/left_right_list', light: true, title: "Last Update", value: recent.updated.strftime("%m/%d/%Y at %I:%M%p") %>
  <%= render 'shared/left_right_list', light: false, title: "Population", value: number_to_human(country.population) %>
  <%= render 'shared/left_right_list', light: true, title: "Total Cases", value: number_with_delimiter(recent.total_cases) %>
  <%= render 'shared/left_right_list', light: false, title: "Total Deaths", value: number_with_delimiter(recent.total_deaths) %>
  <%= render 'shared/left_right_list', light: true, title: "Mortality Rate", value: "#{recent.mortality_rate}%" %>
  <%= render 'shared/left_right_list', light: false, title: "Total Infection Rate", value: "#{country.percent_infected}%" %>
  <%= render 'shared/left_right_list', light: true, title: "7 Day Infection Rate", value: "#{growth.round(2)}%" %>

  <%= render 'shared/country_region_select', countries: countries, regions: regions %>
</div>

app/views/shared/_data_box_region.html.erb
<div class="data-box">
  <h3 class="text-center mb-3">Data for <%= region.gsub("_", " ") %></h3>
  <%= render 'shared/left_right_list', light: true, title: "Population", value: number_to_human(total_pop) %>
  <%= render 'shared/left_right_list', light: false, title: "Total Cases", value: number_with_delimiter(total_cases) %>
  <%= render 'shared/left_right_list', light: true, title: "Total Deaths", value: number_with_delimiter(total_deaths) %>
  <%= render 'shared/left_right_list', light: false, title: "Mortality Rate", value: number_with_delimiter(mortality_rate) %>
  <%= render 'shared/left_right_list', light: true, title: "Total Infection Rate", value: number_with_delimiter(spread) %>
  <h5 class="mt-3 text-center">The Countries in this Region</h5>
  <p class="text-center"><%= country_names.join(', ') %></p>
  <%= render 'shared/country_region_select', countries: countries, regions: regions %>
<div>

app/views/shared/_left_right_list.html.erb
<div class="d-flex justify-content-between px-3 align-items-center <%= 'light-contrast' if light%>">
    <p><%= title %></p>
    <p><%= value %></p>
</div>